name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Test
        run: npm run test
