service: aws-shop-gateway-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  profile: rss
  region: eu-central-1

plugins:
  - serverless-bundle

custom:
  bundle:
    ignorePackages:
      - pg-native

functions:
  createProduct:
    handler: src/createProduct.handler
    environment: ${file(.env.yml)}
    events:
      - http:
          path: /products
          method: post
  getProductsList:
    handler: src/productsList.handler
    environment: ${file(.env.yml)}
    events:
      - http:
          path: /products
          method: get
  getProductsById:
    handler: src/productsById.handler
    environment: ${file(.env.yml)}
    events:
      - http:
          path: /products/{productId}
          method: get
