service: aws-shop-gateway-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: rss
  region: eu-central-1

# plugins:
#   - serverless-bundle

functions:
  getProductsList:
    handler: handler.endpoint
    events:
      - http:
          path: /products
          method: get
