name: Deploy

# Tempory disabled because PRs are not merged
# on:
#   push:
#     branches:
#       - master

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rss-ritual-shop"
          heroku_email: "zenbysel@gmail.com"
