name: Test lambdas

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "src/bff-service/**"
    branches:
      - "task-**"
      - master

jobs:
  lambda-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Test
        run: npm run test
