name: Test bff service

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/bff-service/**"
    branches:
      - "task-**"
      - master

jobs:
  bff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go to bff service
        run: cd src/bff-service

      - name: Install Packages
        run: npm install

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test
