name: Test backend for frontend service

on:
  push:
    branches:
      - master
  # pull_request:
  #   paths:
  #     - "src/bff-service/**"
  #   branches:
  #     - "task-**"
  #     - master

jobs:
  bff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install
        working-directory: ./src/bff-service

      - name: Lint
        run: npm run lint
        working-directory: ./src/bff-service

      - name: Test
        run: npm run test:e2e
        working-directory: ./src/bff-service
